language: swift
osx_image: xcode10.2
xcode_project: CountOnMe.xcodeproj
xcode_scheme: CountOnMe
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 8
install:
  - ./install_swiftlint.sh
script:
  - swiftlint